name: circular_chart_flutter
description: Animated radial and pie charts for Flutter
version: 0.0.5
homepage: https://github.com/afandiyusuf/flutter_circular_chart

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: any

environment:
  sdk: '>=2.17.0 <4.0.0'
